### ISSUE TITLE
Menu Builder: Category Tree is not configurable (no selection of ind. items possible)

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#1043] opened 2024-03-12 09:29 UTC
The Category Tree for menu items should be *configurable*: it should be possible for shop admin to **exclude some categories** from the category tree for display in a menu item, or even display just **one category** in a menu item. 

There is only the **workaround** with individual link to a Category now.

**Comment by mgesing** [comment] 2024-12-20 12:40
Duplicate of #501.

**Closed by mgesing** 2024-12-20 12:40 UTC
Labels: enhancement
