### ISSUE TITLE
Export Publishing Profile: Email TO entry seems broken for some users/browser

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#1102] opened 2024-05-23 10:15 UTC
**Describe the bug**

in Export / Publishing Profile: the _"email address to" entry field_ seems broken for some users/browser

**To Reproduce**

Regarding UX:

it is difficult / impossible  for some users with some browsers to simply add an Email TO address

It works with advanced copy/pasting tricks!

The wording and help texts here could also be more clearer (what is a "email address to") and helpful!

**Expected behavior**
just paste an email and it works (which it does not ... now)

**Screenshots**
![2024-05-23_12-02-04](https://github.com/smartstore/Smartstore/assets/54363171/df6f3e66-f634-42be-bc57-5af9de1648ff)

**Desktop (please complete the following information):**
 - Smartstore 5.1 / Browser OS: Windows, Mac
 - Browser chrome, safari

**Comment by mgesing** [comment] 2024-05-23 10:54
Any steps to reproduce this? The dropdown of **Email addresses to** on the screenshot seems to not initialize (JavaScript error).

> The wording and help texts here could also be more clearer (what is a "email address to") and helpful!

See the setting's hint: "specifies the email addresses where to send the data to".

**Comment by mgesing** [comment] 2024-07-26 11:46
Duplicate of #757 of `select2` initialization issue.

**Closed by mgesing** 2024-07-26 11:46 UTC
Labels: bug
