### ISSUE TITLE
Showstopper- Arabic date issue

### ISSUE THREAD

**Issue by haythamragab** [smartstore/Smartstore#942] opened 2023-12-16 00:04 UTC
**Describe the bug**
Switch to Arabic and open any screen which has a date it will show an error “out of range date”.

**To Reproduce**
1. Switch to Arabic 
2. Go to administrator section
3. Click on ‘customers’ to list all customers

**Expected behavior**
Out of range date issue .

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ Windows 10 x64]
 - Browser [ chrome, safari]

**Comment by haythamragab** [comment] 2023-12-18 06:10
![Arabic_From_your_online_demo](https://github.com/smartstore/Smartstore/assets/12944691/8bfdbdd6-4fc7-449c-856c-afff961f1a82)

**Comment by mgesing** [comment] 2023-12-18 20:50
Duplicate of #868

**Comment by haythamragab** [comment] 2023-12-18 21:01
@mgesing thanks for your feedback.
Any expectations about the fix for this issue with Arabic language

**Comment by mgesing** [comment] 2023-12-19 08:28
No, there is currently no more precise time frame than milestone 5.2.0. This looks like a fundamental date conversion problem.

**Comment by yassinzaid** [comment] 2024-01-26 17:16
is any one solved this problem in update 5.1 ??

**Comment by yassinzaid** [comment] 2024-01-26 21:18
I fixed my issue after a long time ... Go to your server > Region > additional settings > Tab from top the Date > then change the date of the calendar to 2077 .. it works
![error calendar](https://github.com/smartstore/Smartstore/assets/35197188/69918dfb-479b-4ae3-a01e-9a99fb847cd0)

**Comment by Michael-Herzog** [comment] 2024-02-26 11:26
I don't know how, but this seems to be fixed in the cuurent dev branch. I have reproduced the problem with branch 5.1.0 but not in the current main branch.

Regards

**Closed by Michael-Herzog** 2024-02-26 11:26 UTC
Labels: bug, duplicate
