### ISSUE TITLE
Cron Job Send emails not working

### ISSUE THREAD

**Issue by abberdeen** [smartstore/Smartstore#519] opened 2022-07-18 09:41 UTC
**Describe the bug**
Cron Job Send emails not working

**To Reproduce**
1. Set up Email Accounts.
2. Perform the action after which the email is sent. For example register a user.
3. The system does not send an email, there are no errors in the logs. And the message just stands in line.

**Expected behavior**
An email should be sent. For example, the system should automatically send an email to a new user after registration.
 
**Additional context**
It works if you send it manually, for example, on the preview window, click the send test message button. However, it sends a message with an empty body, and also does not show any errors and is not in the logs.

**Comment by Michael-Herzog** [comment] 2022-07-19 08:09
Hi,
is the task scheduler running in general e.g. the task _Rebuild XML Sitemap_? Please check here **Admin > System > Scheduled Tasks**. 
Regards,
Michael

**Comment by zihniartar** [comment] 2022-07-19 13:12
Hi,

there is a setting in the **web-config** file (located in the root folder). Please open the web.config with an editor and search for "_taskschedulerbaseurl_". the node is commented out, you have to reactivate it and replace the value localhost with your URL in the attribute "value". the path "/taskscheduler" has to remain unchanged.

**Comment by abberdeen** [comment] 2022-07-19 14:07
Hi,

The webconfig file did not have this parameter, but I added:
```
<appSettings>
<add key="sm:TaskSchedulerBaseUrl" value="https://*/taskscheduler" />
</appSettings>
```

**Comment by zihniartar** [comment] 2022-07-19 14:12
I'm sorry, I overlooked the fact that this is Smartstore 5.

The setting must be made in the appsettings.json file. Please search there for TaskSchedulerBaseUrl.

**Comment by abberdeen** [comment] 2022-07-19 15:31
Thanks for the clarification.

I got the following error, please tell me what could be causing this:
**`Smartstore.Scheduling.DbTaskStore`**

```
The LINQ expression 'OUTER APPLY 
(
    SELECT TOP(1) s0.Id, s0.Error, s0.FinishedOnUtc, s0.IsRunning, s0.MachineName, s0.ProgressMessage, s0.ProgressPercent, s0.StartedOnUtc, s0.SucceededOnUtc, s0.ScheduleTaskId
    FROM ScheduleTaskHistory AS s0
    WHERE (s.Id == s0.ScheduleTaskId) && (Not(s.RunPerMachine) || (s.RunPerMachine && (s0.MachineName == @__machineName_1)))
    ORDER BY s0.StartedOnUtc DESC, s0.Id DESC
) AS t' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

```
The LINQ expression 'OUTER APPLY 
(
    SELECT TOP(1) s0.Id, s0.Error, s0.FinishedOnUtc, s0.IsRunning, s0.MachineName, s0.ProgressMessage, s0.ProgressPercent, s0.StartedOnUtc, s0.SucceededOnUtc, s0.ScheduleTaskId
    FROM ScheduleTaskHistory AS s0
    WHERE (s.Id == s0.ScheduleTaskId) && (Not(s.RunPerMachine) || (s.RunPerMachine && (s0.MachineName == @__machineName_1)))
    ORDER BY s0.StartedOnUtc DESC, s0.Id DESC
) AS t' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.System.InvalidOperationException: The LINQ expression 'OUTER APPLY 
(
    SELECT TOP(1) s0.Id, s0.Error, s0.FinishedOnUtc, s0.IsRunning, s0.MachineName, s0.ProgressMessage, s0.ProgressPercent, s0.StartedOnUtc, s0.SucceededOnUtc, s0.ScheduleTaskId
    FROM ScheduleTaskHistory AS s0
    WHERE (s.Id == s0.ScheduleTaskId) && (Not(s.RunPerMachine) || (s.RunPerMachine && (s0.MachineName == @__machineName_1)))
    ORDER BY s0.StartedOnUtc DESC, s0.Id DESC
) AS t' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Smartstore.Scheduling.DbTaskStore.RetryOnTransientException(Int32 attemp, Exception ex) in C:\Users\***\src\Smartstore.Core\Platform\Scheduling\Services\DbTaskStore.cs:line 336
   at Smartstore.Utilities.Retry.RunAsync[T](Func`1 operation, Int32 attempts, Nullable`1 wait, Action`2 onFailed) in C:\Users\***\src\Smartstore\Utilities\Retry.cs:line 129
   at Smartstore.Scheduling.DbTaskStore.GetPendingTasksAsync() in C:\Users\***\src\Smartstore.Core\Platform\Scheduling\Services\DbTaskStore.cs:line 178
   at Smartstore.Scheduling.TaskSchedulerMiddleware.Poll(HttpContext context, ITaskStore taskStore, ITaskExecutor executor, IDictionary`2 taskParameters) in C:\Users\***\src\Smartstore\Scheduling\TaskSchedulerMiddleware.cs:line 59
   at Smartstore.Scheduling.TaskSchedulerMiddleware.Invoke(HttpContext context, ITaskStore taskStore, ITaskExecutor executor) in C:\Users\***\src\Smartstore\Scheduling\TaskSchedulerMiddleware.cs:line 48
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Smartstore.Core.Localization.RequestCultureMiddleware.Invoke(HttpContext context, IWorkContext workContext) in C:\Users\***\src\Smartstore.Core\Platform\Localization\Services\RequestCultureMiddleware.cs:line 71
   at Smartstore.Core.Bootstrapping.CheckoutBootstrappingExtensions.<>c.<<UseCheckoutState>b__0_0>d.MoveNext() in C:\Users\***\src\Smartstore.Core\Checkout\Bootstrapping\CheckoutBootstrappingExtensions.cs:line 30
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Smartstore.Engine.Initialization.ApplicationInitializerMiddleware.Invoke(HttpContext context) in C:\Users\***\src\Smartstore\Engine\Initialization\ApplicationInitializerMiddleware.cs:line 70
   at Smartstore.Core.Logging.RequestLoggingMiddleware.InvokeAsync(HttpContext httpContext, IWebHelper webHelper, IWorkContext workContext) in C:\Users\***\src\Smartstore.Core\Platform\Logging\Serilog\RequestLoggingMiddleware.cs:line 80
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by muratcakir** [comment] 2022-07-19 19:13
Maybe MySql? We'll investigate.

**Comment by abberdeen** [comment] 2022-07-20 06:37
Yes I use MySQL. thanks!

**Comment by mgesing** [comment] 2022-07-20 09:03
I cannot reproduce that. Are you using Smartstore.Data.MySql with the current Pomelo version 6.0.1? What MySql version are you using (8.0.27 in my case)? Have you ever cleaned up the entire solution and your NuGet cache?

For me, a different SQL is generated for the query in question (DbTaskStore.cs, line 197). No 'OUTER APPLY', no 'SELECT TOP(1)'. Instead a 'LEFT JOIN LATERAL'.

Independently of this, the query could be written in a different way 'LEFT JOIN (SELECT...)' which may be more simpler for the database provider to translate but that 'LEFT JOIN LATERAL' looks fine to me.

**Comment by abberdeen** [comment] 2022-07-20 18:40
My apologies, it turns out I'm using MariaDB instead of pure MySQL.

System:
.NET 6.0.4
Microsoft Windows 10.0.17763 (x64)
Microsoft-IIS/10.0
10.5.15-MariaDB

Loaded Libraries:
```
Smartstore.Data.MySql, Version=5.0.0.0
Pomelo.EntityFrameworkCore.MySql, Version=6.0.1.0
FluentMigrator.Runner.MySql, Version=3.3.2.0
MySqlConnector, Version=2.0.0.0,
Microsoft.EntityFrameworkCore.Bulk.MySql, Version=6.0.0.0
```

**Comment by mgesing** [comment] 2022-07-21 09:37
Based on the compatibility description your MariaDB version 10.5.15 is supported by Pomelo.EntityFrameworkCore.MySql. But if this is really always the case in practice I can't say, because I never tested MariaDB.

**Comment by Macka323** [comment] 2022-11-12 13:00
I am experiencing the same problem. I have MySql installed on 3 different machines.
1. Laptop - cron jobs work
Asus Tuf 17
win 11
16 BG ram

2. Laptop - cron jobs don't work
Hp 250 
win 10
4 GB ram

3. Conmputer - cron jobs don't work
Hp Prodesk
win 11
4 GB ram

**Comment by Macka323** [comment] 2022-12-27 00:03
Hello, I think i found a fix for this bug.
Just install [dotnet 6 sdk](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)

**Closed** 2023-03-30 18:51 UTC
Labels: bug, review

**Comment by Algorithman** [comment] 2023-04-04 15:52
The OUTER APPLY is caused by old mariaDB versions, update your version to the latest stable (and probably upgrade your databases) and it'll be gone.

**Comment by Algorithman** [comment] 2023-04-05 16:56
Ohh, was I off. Even newer MariaDb didn't work.

But this does:

````            
var query =
                from t in Db.TaskDescriptors
                where t.NextRunUtc.HasValue && t.NextRunUtc <= now && t.Enabled
                select new
                {
                    Task = t,
                };

            var tasks = await ExecuteWithRetry(() => query.ToListAsync());

            var pendingTasks = tasks
                .Select(x =>
                {
                    x.Task.LastExecution = x.Task.ExecutionHistory
                        .Where(th => !x.Task.RunPerMachine || (x.Task.RunPerMachine && th.MachineName == machineName))
                        .OrderByDescending(th => th.StartedOnUtc)
                        .ThenByDescending(th => th.Id)
                        .FirstOrDefault();
                    return x.Task;
                })
                .Where(x => x.IsPending)
                .OrderByDescending(x => x.Priority)
                .ThenBy(x => x.NextRunUtc.Value)
                .ToList();
````

Since the ExecutionHistory is filled anyway, there should be no downside to moving the inner query.

**Comment by muratcakir** [comment] 2023-04-05 19:20
I used the other already existing [SQLite query variant](https://github.com/smartstore/Smartstore/blob/6605dec874092a53177ab1b8c0972dfb8ebb5b4f/src/Smartstore.Core/Platform/Scheduling/Services/DbTaskStore.cs#L233), because it does not fully materialize the `Task.TaskExecutionInfos` collection. This is the commit: 6605dec

Thank you for your contribution.
