### ISSUE TITLE
Feature Request: Grouping Product Specifications for Enhanced Organization

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#989] opened 2024-01-29 09:32 UTC
I propose a new feature that would greatly enhance the user experience and organization of *product specifications* e.g. on the product detail page. (This was suggested by a tech distributor/developer)

**Feature Description:**
Create a new ability to *group* product specifications. Currently, in the Smartstore system, we have the functionality to list product specifications (see screenshot), but there's no option to categorize or *group* these specifications, and add *specific headers* for the groups.

**Use Case Example:**
For instance, if we are listing a laptop, we could group specifications under categories like "Processor," "Memory," "Display," etc. Each category would then contain relevant specifications. 

**Here's a brief example:**

- **Processor** <-- NEW: Group Title
   - Manufacturer: Intel <-- NEW: Group Members ...
   - Processor Family: Intel Core i7
   - Processor: i7-1335U
   - Cores: 10
   - Cache: 12 MB

- **Memory** <-- NEW: Group Title
   - RAM Size: 16 GB
   - RAM Layout: 2 x 8 GB
   - Slots: 2 x SODIMM
   - RAM Speed: 5200 MHz

- **Display** <-- NEW: Group Title
   - Size: 40.3 cm (16")
   - Type: Full HD
   - Resolution: 1920 x 1080 pixels
   - Panel: IPS

**Benefits:**
- **Improved Readability:** This grouping would make it easier for customers to read and understand the specifications, esp. on *very large spec lists* in many B2B szenarios!
- **Better Organization:** It will help in organizing the product information in a *more structured and aesthetically pleasing* way.
- **Enhanced User Experience:** By providing information in a grouped format, it can enhance the overall *shopping experience* for users.

Looking forward to your positive response.

![attribute](https://github.com/smartstore/Smartstore/assets/54363171/182017d3-5619-4d21-b4f5-07829f2174f9)

**Comment by mgesing** [comment] 2024-01-29 09:38
Duplicate of #988.

**Closed by mgesing** 2024-01-29 09:38 UTC
Labels: duplicate
