### ISSUE TITLE
Language culture  

### ISSUE THREAD

**Issue by moflehsami** [smartstore/Smartstore#868] opened 2023-10-30 14:34 UTC
**Describe the bug**
when i added arabic lang with culture [ar-SA] 
the next error appeared with any view data has datetime 
(ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive. (Parameter 'time'))

cause Arabic calendrer need specific time converter  or you can make the Gregorian calendrer is default  for Arabic culture  
for ar the number of day is 354. 
the date today is 1445/4/16
while you setup the range of the accepted date between 1900 - 2077

**Comment by yassinzaid** [comment] 2024-01-26 21:15
I fixed my issue after a long time ... Go to your server > Region > additional settings > Tab from top the Date > then change the date of the calendar to 2077 .. it works 
![error calendar](https://github.com/smartstore/Smartstore/assets/35197188/fdc565ce-5f0b-44bc-87ef-9a7a1dd8fecc)

**Comment by Michael-Herzog** [comment] 2024-02-26 11:26
I don't know how, but this seems to be fixed in the cuurent dev branch. I have reproduced the problem with branch 5.1.0 but not in the current main branch.

Regards

**Closed by Michael-Herzog** 2024-02-26 11:26 UTC
Labels: bug, review
