### ISSUE TITLE
Pagebuilder language dependency

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#923] opened 2023-12-07 13:18 UTC
**Is your feature request related to a problem? Please describe.**
Since we quite often attend trade fairs we would like to for example tell our French customers when we're in Paris again. At the moment i don't see any possibility to display a Pagebuilder page only for a certain language or did I miss something?

Also: Is there a way to add custom blocks to the Pagebuilder? I see the ViewComponent Block there, but editing parameters etc in the backend (not as json but with actual input fields) would be nice.

**Comment by muratcakir** [comment] 2023-12-12 00:16
Dupe of #934

**Closed by muratcakir** 2023-12-12 00:16 UTC
Labels: enhancement
